"""Baseline schema before personal accounts."""
import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_benchmark_price_symbol_date')
    )
    op.create_index(op.f('ix_benchmark_prices_date'), 'benchmark_prices', ['date'], unique=False)
    op.create_index(op.f('ix_benchmark_prices_symbol'), 'benchmark_prices', ['symbol'], unique=False)
    op.create_table('cache_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'key', name='uq_cache_ns_key')
    )
    op.create_index(op.f('ix_cache_entries_expires_at'), 'cache_entries', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cache_entries_key'), 'cache_entries', ['key'], unique=False)
    op.create_index(op.f('ix_cache_entries_namespace'), 'cache_entries', ['namespace'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('is_example', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('raw_provider_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_key', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_provider_responses_content_hash'), 'raw_provider_responses', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_provider_responses_resource_key'), 'raw_provider_responses', ['resource_key'], unique=False)
    op.create_table('analyst_consensus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Integer(), nullable=False),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('sell', sa.Integer(), nullable=False),
    sa.Column('strong_sell', sa.Integer(), nullable=False),
    sa.Column('consensus_label', sa.String(length=16), nullable=True),
    sa.Column('target_high', sa.Float(), nullable=True),
    sa.Column('target_low', sa.Float(), nullable=True),
    sa.Column('target_consensus', sa.Float(), nullable=True),
    sa.Column('target_median', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('analyst_count', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_analyst_consensus_company')
    )
    op.create_index(op.f('ix_analyst_consensus_company_id'), 'analyst_consensus', ['company_id'], unique=False)
    op.create_table('analyst_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('price_target', sa.Float(), nullable=True),
    sa.Column('rating_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_ratings_company_id'), 'analyst_ratings', ['company_id'], unique=False)
    op.create_index(op.f('ix_analyst_ratings_external_id'), 'analyst_ratings', ['external_id'], unique=False)
    op.create_index(op.f('ix_analyst_ratings_rating_date'), 'analyst_ratings', ['rating_date'], unique=False)
    op.create_table('catalyst_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('drug_program', sa.String(length=256), nullable=False),
    sa.Column('indication', sa.String(length=256), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('trial_phase', sa.String(length=32), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalyst_events_company_id'), 'catalyst_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalyst_events_expected_date'), 'catalyst_events', ['expected_date'], unique=False)
    op.create_index(op.f('ix_catalyst_events_external_id'), 'catalyst_events', ['external_id'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('raw_response_id', sa.Integer(), nullable=True),
    sa.Column('accession_number', sa.String(length=32), nullable=False),
    sa.Column('form', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=4), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_provider_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_accession_number'), 'filings', ['accession_number'], unique=False)
    op.create_index(op.f('ix_filings_company_id'), 'filings', ['company_id'], unique=False)
    op.create_index(op.f('ix_filings_period_end'), 'filings', ['period_end'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_price_company_date')
    )
    op.create_index(op.f('ix_market_prices_company_id'), 'market_prices', ['company_id'], unique=False)
    op.create_index(op.f('ix_market_prices_date'), 'market_prices', ['date'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related', sa.String(length=128), nullable=True),
    sa.Column('sentiment_label', sa.String(length=12), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_method', sa.String(length=12), nullable=False),
    sa.Column('impact', sa.String(length=12), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'external_id', name='uq_news_company_ext')
    )
    op.create_index(op.f('ix_news_articles_company_id'), 'news_articles', ['company_id'], unique=False)
    op.create_index(op.f('ix_news_articles_external_id'), 'news_articles', ['external_id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_table('signal_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('inputs_snapshot', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_runs_as_of_date'), 'signal_runs', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_signal_runs_company_id'), 'signal_runs', ['company_id'], unique=False)
    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('concept', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('xbrl_concept', sa.String(length=128), nullable=True),
    sa.Column('taxonomy', sa.String(length=16), nullable=True),
    sa.Column('accession_number', sa.String(length=32), nullable=True),
    sa.Column('form', sa.String(length=16), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=4), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('quality_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metrics_company_id'), 'financial_metrics', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_metrics_concept'), 'financial_metrics', ['concept'], unique=False)
    op.create_index(op.f('ix_financial_metrics_filing_id'), 'financial_metrics', ['filing_id'], unique=False)
    op.create_index(op.f('ix_financial_metrics_period_end'), 'financial_metrics', ['period_end'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Baseline downgrade is intentionally disabled to preserve research data.")
